#version: "3.7"

services:
  ui-app:
    container_name: ui-app
    image: ui-app
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    #      -  /app/node_modules
    command: sh -c "sleep 5 && yarn && yarn dev"